services:
  - type: web
    name: grafana
    env: docker
    plan: free

    dockerfilePath: ./Dockerfile

    envVars:
      - key: GF_USERS_DEFAULT_THEME
        value: light
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: admin123
